---
title: "BCB 520:: Foundations of Data Visualization"
listing:
  contents: posts
  sort: "date desc"
  type: grid
  categories: true
  sort-ui: true
  filter-ui: true
page-layout: full
title-block-banner: true
---

# **// About**

This class will help students establish a core understanding of data visualization. We will consider how data type (including tabular, network, and spatial data) interacts with visualization task to guide design choices. Diverse types of visual encodings and how they relate to human perception will be presented, along with practical exercises using the R and Python programming languages. Upon completion of the course, students will understand **WHY** particular visualization approaches are effective for a given data set and **HOW** to implement those visualizations using the language of their choice. The course is designed to be "discipline agnostic" - each student is encouraged to use data sets that they deem important / interesting. The goal is to have students learn how to develop visualizations that are relevant to their own disciplinary interests.

## Quick Links

I am maintaining the course here and on its [CANVAS PAGE](https://canvas.uidaho.edu/courses/25613){target="_blank"} (for enrolled students).

[SYLLABUS](syllabus.qmd)

[Barrie's GitHub](https://github.com/ProfessorPolymorphic){target="_blank"}

### Student Repositories

[KB GitHub](https://github.com/konradbailey) and [KB Portfolio](https://konradbailey.github.io/BCB520.Portfolio.V2/){target="_blank"}

[HS GitHub](https://github.com/heidihosellmann) and [HS Porfolio](https://heidihosellmann.github.io/BCB520Portfolio/)

[YG GitHub](https://github.com/yaotian-gao) and [YG Porfolio](https://yaotian-gao.github.io/BCB-Quarto-Blog-/)

[RS GitHub](https://github.com/robynsteveley) and [RS Porfolio](https://robynsteveley.github.io/BCB520PortfolioGithub/)

[GT GitHub](https://github.com/gt0107) and [GT Porfolio](https://gt0107.github.io/BCB-520-Portfolio/)

[LR GitHub](https://github.com/lripa) and [LR Porfolio](https://lripa.github.io/BCB520GitHub/)

## Learning Resources

[The Functional Art](http://www.thefunctionalart.com)

[GGSIDE!](https://www.business-science.io/code-tools/2021/05/18/marginal_distributions.html) A companion to `ggplot` for making side plots! COOL!

[Awesome Quarto:](https://github.com/mcanouil/awesome-quarto){target="_blank"} A potentially interesting repository of Quarto documents, talks, tools, examples, etc.

[The MockUp Blog - TABLES!](https://themockup.blog/posts/2022-06-13-gtextras-cran/){target="_blank"} This blog post explores the R packages `gt` and `gtextras` which will help us up our table game!

[Riffomonas Project](https://www.youtube.com/@Riffomonas/featured){target="_blank"}: Pat Schloss is a [Professor at the University of Michigan](https://www.schlosslab.org){target="_blank"}. The Riffomonas Project is his Youtube channel, which has HUNDREDS of easy to follow and amazingly useful instructional videos on R, ggplot, version control, and literate programming.

[Dr. Tamara Munzner's Website:](https://www.cs.ubc.ca/~tmm/){target="_blank"} It isn't fancy, but Dr. Munzner's website has tons of resources from her textbook and the many data visualization courses she has offered. This includes recorded lectures that align directly with the chapters of the text, much like what we are using.

[Cheat Sheets:](https://posit.co/resources/cheatsheets/){target="_blank"} So many visual guides for many R packages, including the tidyverse, ggplot, dplyr, etc.

[Learning Vis Tools: Teaching Data Visualization Tutorials](https://ieeexplore.ieee.org/document/8933751){target="_blank"} An interesting paper for discussion as we forge the structure for this class.

# **// Posts**
